version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: Install Bats Dependencies
          command: make deps
      - run:
          name: Execute Bats Test Suite
          command: make test
